# -*- coding: utf-8 -*-
"""SistemaBancarioV1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b-NRdLnmA6Mq4NxzbBjCTpzBNZMqDwM3
"""

class ContaBancaria:
    def __init__(self):
        self.saldo = 0.0
        self.transacoes = []
        self.saques_realizados = 0

    def deposito(self, valor):
        if valor > 0:
            self.saldo += valor
            self.transacoes.append(f'Depósito: +R${valor:.2f}')
            return f'Depósito de R${valor:.2f} realizado com sucesso.'
        else:
            return 'O valor do depósito deve ser maior que zero.'

    def saque(self, valor):
        if valor > 0 and valor <= self.saldo and self.saques_realizados < 3 and valor <= 500:
            self.saldo -= valor
            self.transacoes.append(f'Saque: -R${valor:.2f}')
            self.saques_realizados += 1
            return f'Saque de R${valor:.2f} realizado com sucesso.'
        elif valor <= 0:
            return 'O valor do saque deve ser maior que zero.'
        elif valor > 500:
            return 'O valor máximo de saque é R$500.'
        elif self.saques_realizados >= 3:
            return 'Limite de saques diários atingido.'
        else:
            return 'Saldo insuficiente para realizar o saque.'

    def extrato(self):
        extrato = f'\nSaldo atual: R${self.saldo:.2f}\n'
        extrato += "Histórico de Transações:\n"
        for i, transacao in enumerate(self.transacoes, start=1):
            extrato += f"{i}: {transacao}\n"
        return extrato


def main():
    conta = ContaBancaria()

    while True:
        print("\nBem-vindo ao Banco Pytloun")
        print("Escolha uma opção:")
        print("1: Depósito")
        print("2: Saque")
        print("3: Extrato")
        print("4: Sair")

        opcao = input("Digite o número da opção desejada: ")

        if opcao == '1':
            valor = float(input("\nDigite o valor do depósito: "))
            resultado = conta.deposito(valor)
            print(resultado)
        elif opcao == '2':
            valor = float(input("\nDigite o valor do saque: "))
            resultado = conta.saque(valor)
            print(resultado)
        elif opcao == '3':
            resultado = conta.extrato()
            print(resultado)
        elif opcao == '4':
            print("\nObrigado por utilizar os nossos serviços!")
            break
        else:
            print("\nOpção inválida. Tente novamente.")


if __name__ == "__main__":
    main()